### ISSUE TITLE
wrong paper for type soundness proof?

### ISSUE THREAD

**Issue by pnwamk** [ponylang/ponylang.github.io#100]
In the 'Pony is type safe' section of the 'Discover' page, there is a link whose text alludes to a proof of type soundness (_Really type safe. There’s a mathematical proof and everything._) that doesn't exist in the linked paper.

Is that the wrong paper to put there?

**Comment by Theodus** [comment]
@pnwamk are you questioning the operational semantics of the language, the definition of the type system in Fig. 3, or are you getting a bad link? It should be a paper titled "Deny Capabilities for Safe, Fast Actors".

**Comment by plietar** [comment]
I think this is the version that was published at AGERE '15.

There's a longer, unpublished, version of this paper at https://www.doc.ic.ac.uk/~scd/fast-cheap.pdf which includes the soundness proofs

**Comment by SeanTAllen** [comment]
@Theodus @plietar I think its reasonable to host both versions of the paper on the site and link the "proof" to the older version that @plietar points out. Thoughts?

**Comment by Theodus** [comment]
Sounds good to me.
