### ISSUE TITLE
New Website Design/Organization

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponylang.github.io#11]
The website needs a new design with a consistent branding, use of font etc.

As part of this, it needs a strategy for organizing information.

I'm think that we have a top navigation bar that is present on all pages operates in "normal" fashion that most programming websites have. I mention this only so that the design can take this into account. I don't think it is the most important thing we need at the moment. 

I'm most interested in getting in place and initial home page that takes into account that the 4 primary types of visitors we have and guiding each to their own section of the site where we can collect together information that would most interest them and give them a "guided tour" experience.

The four primary areas:
## "Discover"

Discover would be information for people who have just heard about Pony and are coming to get more information to find out at a high level what Pony is. Our key goal here should be able to get these people interested in Pony and wanting to start learning Pony. The assumption here is that, at this time, "discover" is targeting people who have a technical background and some level of programming experience. We can't however assume that they know what the actor model is, capabilities, high performance etc. We can use those terms as long as we define them.

Once "Pony for X" content is further along, we might want to link to it from here.
## "Learn"

Learn collects together the various learning resources that we have and helps guide people through learning Pony. "Start here, then do this". It should contain overviews of the various materials we have. Tutorial, Pony Patterns, "Planet Pony" etc etc. Also link to standard library and what not. 
## "Reference"

Target audience is returning Pony users who already know the language and are looking for links to various things, news on the latest items and what not. Releases etc etc
## "Contributor"

Section of the site with content for people who are interested in contributing to Pony. This could be code, infrastructure, design, or what not. 

---

So the main site, when you hit the home page, has some "normal" top nav <to be added later>

a short "what is pony"

followed by some time of text, diagram or something that leads people off to one of the 4 main sections of the site.

---

I'm sure as we add more content we will find content that fits none of the above areas and we will have to address as we find.

Additionally some content will be applicable across multiple areas and will be included in each.

**Comment by kenkeiter** [comment]
"???" = "Reference" ?

**Comment by SeanTAllen** [comment]
Yeah, I like that. "Reference"

**Comment by iktyrrell** [comment]
What about "Contribute" vs "Contributor" i.e. verb, call-to-action?

**Comment by SeanTAllen** [comment]
@iktyrrell yes, that works.

**Comment by iktyrrell** [comment]
![pony homepage wireframe](https://cloud.githubusercontent.com/assets/705279/18176300/ee938bdc-706c-11e6-8bd4-9852a347fda3.png)

Here's a first cut at the homepage - ignore content and specific styles, this is more about general layout. I've taken some inspiration from other languages having a REPL on their homepage - wouldn't need to 'run' to start with, but could just display some nicely formatted code example to give people a feeling for the language up-front.

**Comment by iktyrrell** [comment]
![pony homepage alt](https://cloud.githubusercontent.com/assets/705279/18177694/4d2ece58-7073-11e6-9085-a4b2674d3b0c.png)

Boxes highlighting some of the key features of the language - perhaps with simple diagrams?

**Comment by iktyrrell** [comment]
Possible font pairing:
https://fonts.google.com/specimen/BioRhyme?selection.family=BioRhyme|Open+Sans

**Comment by SeanTAllen** [comment]
I was thinking that Discover, Learn, Contribute are the primary focus of the page after the intro "this is what it is" and they link into sections with content. IE they wouldnt have links etc on the main page beyond "go here if you want to learn more about Pony" that would include, "what is the actor model" etc etc. 

Focus everything on the homepage around those 3 things and guiding people to the correct subsection.

**Comment by iktyrrell** [comment]
![homepage 3 focus](https://cloud.githubusercontent.com/assets/705279/18201705/8f7ca57e-7103-11e6-85c4-d05dfe6fb8b2.png)

What do you think about surfacing some of the community content on the homepage? I think it's important to show activity i.e. it's not a dead project.

What about displaying a code sample right up-front? I don't think it needs to be interactive necessarily (although that would be nice), but I do think it's important that people don't have to dig too deeply to get a flavour of the syntax. Also, just revisiting one of the [hackernews threads](https://news.ycombinator.com/item?id=10902906) and that was a request/complaint.

**Comment by SeanTAllen** [comment]
Sorry for the long delay on this @iktyrrell, I had life and work things come up.

We decided, for the time being, to resurrect some work I had done in the spring with using Tufte-CSS: https://edwardtufte.github.io/tufte-css/. It looks nice and is easy to read.

We are currently focusing on getting all the content in place before returning to design and figuring out a design that would work with the content we've put together and tufte css.

If you are interested in helping out with any of that let me know.

**Comment by iktyrrell** [comment]
@SeanTAllen no probs - I'll take a look at the existing open issues and see if there is anything I can pick up.

**Comment by SeanTAllen** [comment]
they are mostly loose notes and maybe not so helpful but ask away with any questions and i'll fill out details as requested.

**Comment by SeanTAllen** [comment]
Basics of this are in place.
