### ISSUE TITLE
Slack Channel for Pony Users

### ISSUE THREAD

**Issue by norbertfuhs** [ponylang/ponylang.github.io#127]
Hi,

is there a Slack channel for Pony Users and people new to Pony?

I think something like the Go community has doone with Gophers on Slack?

**Comment by SeanTAllen** [comment]
There's the #ponylang channel on Freenode in IRC. 

We prefer to keep issue trackers to "actionable items". The best place for questions like this would be the mailing list or the #irc channel (although in the case of the IRC channel, that wouldn't have helped here).

See: https://www.ponylang.org/learn/#getting-help
