### ISSUE TITLE
New Site: Add recent talks and articles

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponylang.github.io#14]
This content exists on the current site. Needs to be slotted into new IA.

**Comment by SeanTAllen** [comment]
Perhaps this is part of the blog?

Or we have a blog and news?

I think I'd rather have a single blog/news feed.

@aturley thoughts?

**Comment by SeanTAllen** [comment]
I'm thinking this should be incorporated into "Planet Pony"

**Comment by Praetonus** [comment]
As said on IRC, [this talk](https://www.youtube.com/watch?v=R6T8ytKV6dc) isn't linked from ponylang.org.

**Comment by SeanTAllen** [comment]
@Praetonus added to "Planet Pony"

**Comment by SeanTAllen** [comment]
These have all been added to "Planet Pony"
