### ISSUE TITLE
New Site: FAQ

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/ponylang.github.io#16]
Add FAQs

We could have FAQs by section or a single page.

Ideally, we use partials to include only section appropriate FAQs but add a link to a page that combines them all together.

**Comment by SeanTAllen** [comment]
After more thought, I'm leaning strongly towards partials that cover FAQs by type "discover", "learn", "contribute" that can be combined into a single page as well.

However step 1: single page. can be organized and broken up from there...

**Comment by aturley** [comment]
Eventually it would be nice to break them out, but I agree that consolidating in one place initially is a good idea. It will give us a chance to see what we have and get a view of where the natural divisions might be.

**Comment by SeanTAllen** [comment]
I'll put in a top level FAQ that we can add to while we are developing. Then we need to make sure to pick a "final home" before merging to master.

**Comment by SeanTAllen** [comment]
Added.
