### ISSUE TITLE
Last Week in Pony - October 15, 2017

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#176]

**Comment by SeanTAllen** [comment]
0.19.3 was released:

https://www.ponylang.org/blog/2017/10/0.19.3-released/

**Comment by SeanTAllen** [comment]
Audio from the October 11 Pony development sync:

https://pony.groups.io/g/dev/files/Pony%20Sync/2017_10_11

**Comment by SeanTAllen** [comment]
RFC issue: Add docstrings for class/actor members

https://github.com/ponylang/rfcs/issues/106

**Comment by SeanTAllen** [comment]
RFC issue: Type parameter constraint syntax for safe matches.

https://github.com/ponylang/rfcs/issues/105
