### ISSUE TITLE
Link to the current language and API reference documentation on the home page

### ISSUE THREAD

**Issue by marshray** [ponylang/ponylang.github.io#199]
The language and API docs represent a substantial part of the material on ponylang.org. This info is probably an extremely common reason people visit ponylang.org, and when they do, they will often have a problem in mind. So it should be easy to locate without too much fuss.

Ensure link(s) to the current language and API reference documentation are prominently visible directly on the home page.

(From discussion at #179)

**Comment by SeanTAllen** [comment]
This is already there on the homepage.
