### ISSUE TITLE
Last Week in Pony - November 19, 2017

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#204]

**Comment by SeanTAllen** [comment]
Audio from the November 15, 2017 Pony development sync:

https://pony.groups.io/g/dev/files/Pony%20Sync/2017_11_15

**Comment by SeanTAllen** [comment]
Runtime backpressure merged to master. Blog post coming that discusses in more detail to go along with the release:

https://github.com/ponylang/ponyc/commit/1104a6ccc182d94e3ec25afa4a2d028d6c642cc4
