### ISSUE TITLE
Last Week in Pony, December 3, 2017

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#211]

**Comment by SeanTAllen** [comment]
Audio from the November 29 Pony development sync:

https://pony.groups.io/g/dev/files/Pony%20Sync/2017_11_29

**Comment by SeanTAllen** [comment]
Pony-kafka version released that is up-to-date with the latest changes on ponyc master:

https://github.com/WallarooLabs/pony-kafka/releases/tag/0.3.0
