### ISSUE TITLE
Last Week in Pony - December 10, 2017

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#214]

**Comment by SeanTAllen** [comment]
Pony-msgpack 0.2.0 released:

https://github.com/SeanTAllen/pony-msgpack/releases/tag/0.2.0

Adds a lowel level API for decoding MessagePack serialized data.

**Comment by SeanTAllen** [comment]
Audio from the December 6, 2017 Pony development sync:

https://pony.groups.io/g/dev/files/Pony%20Sync/2017_12_06
