### ISSUE TITLE
Last Week in Pony - March 04, 2018

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#252]

**Comment by SeanTAllen** [comment]
Audio from the February 28th Pony development sync:

https://pony.groups.io/g/dev/files/Pony%20Sync/2018_02_28

**Comment by SeanTAllen** [comment]
MQTT client in Pony  => https://github.com/epiceric/pony-mqtt

**Comment by mfelsche** [comment]
Has already been announced here https://www.ponylang.org/blog/2018/02/last-week-in-pony---february-11-2018/
