### ISSUE TITLE
Last Week In Pony - March 11, 2018

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#254]
Yes, add your `Last Weeks Playground` links as comments below!

**Comment by MightyAlex200** [comment]
My [submission](https://playground.ponylang.org/?gist=dc16ebcb1b75682bd385b7b9c078fb46) is quite simple, but I hadn't ever seen anything like this in any other language and I thought it was cool that Pony can do this.

**Comment by SeanTAllen** [comment]
I've been working on improving performance of `TCPConnection` when using `expect`. If you are interested in some gory guts, have a peek at the code. Note, its fairly undocumented: https://github.com/wallaroolabs/pony-network-tests

**Comment by SeanTAllen** [comment]
New Ponybench RFC has been merged to master:

https://github.com/ponylang/ponyc/pull/2578

**Comment by SeanTAllen** [comment]
Compile time expressions RFC accepted:

https://github.com/ponylang/rfcs/blob/master/text/0053-compile-time-expression.md
