### ISSUE TITLE
Last Week in Pony - April 2, 2018

### ISSUE THREAD

**Issue by slfritchie** [ponylang/ponylang.github.io#264]
Borrowed from @mfelsche, and assuming that April Fool's Day is the next date in the series....

Hey you, wanna submit a Last Weeks Playground link?
Just add your link with some description of what it exhibits as a comment here and don't forget to vote on other submissions.

**Comment by slfritchie** [comment]
The offline API doc browser work announced by Borja <borjaocook@gmail.com> on the Pony user mailing list is pretty nifty.

Announcement: https://pony.groups.io/g/user/message/1619
GitHub repo: https://github.com/ergl/pony-docset

**Comment by mfelsche** [comment]
The audio of the weekly development sync has been uploaded: https://pony.groups.io/g/dev/files/Pony%20Sync/2018_03_28

**Comment by mfelsche** [comment]
A new version of ponycheck has been released, now supporting asynchronous properties: https://github.com/mfelsche/ponycheck/releases/tag/0.3.0
