### ISSUE TITLE
Have standard library documentation on the site

### ISSUE THREAD

**Issue by aturley** [ponylang/ponylang.github.io#3]
It would be helpful if the standard library documentation could be read somewhere on the site.

**Comment by SeanTAllen** [comment]
can you clarify?

**Comment by aturley** [comment]
I see now that the documentation is available [here](http://www.ponylang.org/ponyc/). I didn't realize that existed, so this issue can be closed.

Currently the only place you can find this link is in README.md for ponyc. I think there should be links to this page from the main ponylang.org page and the tutorial. I'll open separate issues on those.

**Comment by SeanTAllen** [comment]
@aturley ponylang.org is going to undergo a major facelift in the not so distant future

**Comment by MrMormon** [comment]
@SeanTAllen What's on the menu?
