### ISSUE TITLE
Last Week in Pony - July 1, 2018

### ISSUE THREAD

**Issue by mfelsche** [ponylang/ponylang.github.io#306]

**Comment by SeanTAllen** [comment]
Audio from the June 20, 2018 Pony development sync is now available:

https://pony.groups.io/g/dev/files/Pony%20Sync/2018_06_20

**Comment by SeanTAllen** [comment]
RFC 59 "Formal Viewpoint Adaptation" has been accepted.

https://github.com/ponylang/rfcs/blob/master/text/0059-formal-viewpoint-adaptation.md

**Comment by SeanTAllen** [comment]
RFC 58: Partial Arithmetic has been accepted.

https://github.com/ponylang/ponyc/issues/2814

**Comment by SeanTAllen** [comment]
RFC 57: SSL ALPN has been accepted.

https://github.com/ponylang/rfcs/blob/master/text/0057-ssl-alpn.md

**Comment by SeanTAllen** [comment]
Andrew Turley is also doing a Pony tutorial in the NYC area on July 11th:

https://ponylang101.splashthat.com/

**Comment by SeanTAllen** [comment]
Audio from the June 27 Pony development sync is available:

https://pony.groups.io/g/dev/files/Pony%20Sync/2018_06_27

**Comment by SeanTAllen** [comment]
Brian Otto wrote in to the mailing list with some interesting news:

```
Hi Everyone,

I have been working on a Win32 wrapper over the last couple weeks, and it's far enough along, that I thought I would mention it here.

There is a lot of boilerplate you need to get working, just to display a window in the Win32 API, and so this code does it all for you. I've got it to a point where you can create basic windows and controls now, and it has an example on how you can do message and event handling (compile with ponyc -d to see the messages). There is an example of drawing to the window using Cairo too (the required DLL is in the winCairo directory), and I got wide character support working as well. So it should be enough for anyone interested in playing around with the API. I'll be wrapping more of it as time goes on.

https://github.com/BrianOtto/pony-win32 (ISC License)

Cheers!
Brian
```

**Comment by SeanTAllen** [comment]
Pony 0.24.0 has been released:

https://www.ponylang.org/blog/2018/06/0.24.0-released/
