### ISSUE TITLE
broken link in sandbox help/readme

### ISSUE THREAD

**Issue by MrMormon** [ponylang/ponylang.github.io#4]
At the end:

How you can install the Pony compiler and tools on your local machine is 
explained [here](http://tutorial.ponylang.org/getting-started/installation/).

...should be http://tutorial.ponylang.org/getting-started/installation.html

**Comment by SeanTAllen** [comment]
Thanks. I removed the sandbox from the website.

The source isn't on github which makes it hard to maintain, no one can contribute fixes etc. 
It was a lingering issue. We'll be looking at doing another sandbox at some point. If anyone
want to take that on, get in touch.

**Comment by MrMormon** [comment]
What do you mean? The website still links to the sandbox, which still works.

**Comment by SeanTAllen** [comment]
It means I did it on a fork accidentally. Fixed.
