### ISSUE TITLE
Some docstrings are missing

### ISSUE THREAD

**Issue by adam-antonik** [ponylang/ponylang.github.io#97]
The Timers.create page
https://stdlib.ponylang.org/time-Timers/#create

Doe not include the docstring that appears in the 0.14 release

    Create a timer handler with the specified number of slop bits. No slop bits
    means trying for nanosecond resolution. 10 slop bits is approximately
    microsecond resolution, 20 slop bits is approximately millisecond
    resolution.

**Comment by SeanTAllen** [comment]
The docstring for the constructor is getting "lost" in `traits.c` at line 387:

```c
  // Ignore docstring.
  if(ast_id(doc) == TK_STRING)
  {
    ast_set_name(doc, "");
    ast_setid(doc, TK_NONE);
  }
```

where it gets set to `TK_NONE`. What's very odd about this is why trait related code is being run on constructors for actors like Timers.

Additionally, does it make sense to remove the docstring from a trait? It does it the trait is overridden but would this also remove the docstring when not overridden? I'm not sure, that requires more exploration.

**Comment by SeanTAllen** [comment]
@adam-antonik i'm moving this to be on the ponyc repo.

**Comment by SeanTAllen** [comment]
closing in favor of https://github.com/ponylang/ponyc/issues/1993
